version: '3.5'
services:
  zeo:
    build:
      context: .
    image: realestate
    # image: oality/habas34
    volumes:
      - ./var:/plone/var
    command: zeoserver
  instance:
    image: realestate
    # image: oality/habas34
    environment:
      - ZEO_ADDRESS=zeo:8100
      - ZEO_HOST=db
      - ZEO_PORT=8100
    links:
      - zeo:db
    ports:
      - 8080:8080
    command: fg

networks:
  default:
    external:
      name: proxy
